#!/bin/bash

# MTN ClarityAI Infrastructure Deployment Script
# Automates Azure resource deployment with validation and output capture

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
RESOURCE_GROUP="${RESOURCE_GROUP:-clarityai-rg}"
LOCATION="${LOCATION:-eastus}"
DEPLOYMENT_NAME="clarityai-deployment-$(date +%s)"

echo -e "${YELLOW}MTN ClarityAI Infrastructure Deployment${NC}"
echo "========================================"

# Check prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! command -v az &> /dev/null; then
    echo -e "${RED}❌ Azure CLI not found. Install it first: https://aka.ms/azure-cli${NC}"
    exit 1
fi

if ! az account show > /dev/null 2>&1; then
    echo -e "${YELLOW}Not logged in. Run: az login${NC}"
    az login
fi

# Get subscription info
SUBSCRIPTION=$(az account show --query name -o tsv)
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
echo -e "${GREEN}✓ Using subscription: $SUBSCRIPTION (ID: $SUBSCRIPTION_ID)${NC}"

# Create resource group
echo -e "\n${YELLOW}Creating resource group: $RESOURCE_GROUP...${NC}"
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION" > /dev/null
echo -e "${GREEN}✓ Resource group ready${NC}"

# Validate template
echo -e "\n${YELLOW}Validating Bicep template...${NC}"
if az deployment group validate \
    --resource-group "$RESOURCE_GROUP" \
    --template-file main.bicep \
    --parameters parameters.bicepparam > /dev/null; then
    echo -e "${GREEN}✓ Template validation passed${NC}"
else
    echo -e "${RED}❌ Template validation failed${NC}"
    exit 1
fi

# Deploy
echo -e "\n${YELLOW}Deploying infrastructure (this may take 5-10 minutes)...${NC}"
DEPLOYMENT_OUTPUT=$(az deployment group create \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --template-file main.bicep \
    --parameters parameters.bicepparam \
    --output json)

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Deployment completed successfully${NC}"
else
    echo -e "${RED}❌ Deployment failed${NC}"
    exit 1
fi

# Extract outputs
echo -e "\n${YELLOW}Retrieving deployment outputs...${NC}"
OUTPUTS=$(echo "$DEPLOYMENT_OUTPUT" | jq '.properties.outputs')

COSMOS_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.cosmosEndpoint.value')
COSMOS_KEY=$(echo "$OUTPUTS" | jq -r '.cosmosMasterKey.value')
OPENAI_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.openAiEndpoint.value')
OPENAI_KEY=$(echo "$OUTPUTS" | jq -r '.openAiKey.value')
APPINSIGHTS_KEY=$(echo "$OUTPUTS" | jq -r '.appInsightsInstrumentationKey.value')
APPINSIGHTS_CONNECTION=$(echo "$OUTPUTS" | jq -r '.appInsightsConnectionString.value')

# Create environment file
echo -e "\n${YELLOW}Creating .env file for backend...${NC}"
ENV_FILE="../.env.azure"
cat > "$ENV_FILE" << EOF
# Generated by deploy.sh on $(date)
# Copy these to backend/python/.env

CLARITY_COSMOS_ENDPOINT=$COSMOS_ENDPOINT
CLARITY_COSMOS_KEY=$COSMOS_KEY
CLARITY_COSMOS_DATABASE=clarityai
CLARITY_COSMOS_PLANS_CONTAINER=plans
CLARITY_COSMOS_PROFILES_CONTAINER=profiles
CLARITY_COSMOS_USAGE_CONTAINER=usage
CLARITY_COSMOS_AUTH_CONTAINER=auth_users
CLARITY_COSMOS_CHAT_CONTAINER=chat_sessions

CLARITY_AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
CLARITY_AZURE_OPENAI_KEY=$OPENAI_KEY
CLARITY_AZURE_OPENAI_API_VERSION=2024-10-21
CLARITY_AZURE_OPENAI_DEPLOYMENT=clarity-chat

CLARITY_APP_INSIGHTS_KEY=$APPINSIGHTS_KEY
CLARITY_APP_INSIGHTS_CONNECTION_STRING=$APPINSIGHTS_CONNECTION

CLARITY_JWT_SECRET=$(openssl rand -hex 32)
CLARITY_LOG_LEVEL=INFO
EOF

echo -e "${GREEN}✓ Environment file created: $ENV_FILE${NC}"

# Display summary
echo -e "\n${GREEN}========== DEPLOYMENT COMPLETE ==========${NC}"
echo -e "\n${YELLOW}Deployment Summary:${NC}"
echo "  Resource Group: $RESOURCE_GROUP"
echo "  Location: $LOCATION"
echo "  Subscription: $SUBSCRIPTION"
echo ""
echo -e "${YELLOW}Resources Created:${NC}"
echo "  ✓ Cosmos DB Serverless Account"
echo "  ✓ Azure OpenAI Service (gpt-4o-mini)"
echo "  ✓ Application Insights"
echo "  ✓ Log Analytics Workspace"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Review outputs above"
echo "  2. Copy $ENV_FILE to backend/python/.env"
echo "  3. Run: cd ../.. && pip install -r requirements.txt"
echo "  4. Test connections: python -m pytest tests/"
echo "  5. Start backend: uvicorn backend.python.app:app --reload"
echo ""
echo -e "${YELLOW}Cost Monitoring:${NC}"
echo "  View costs: https://portal.azure.com/#view/Microsoft_Azure_Billing/BillingMenuBlade"
echo "  Set alerts: Cost Management + Billing > Budgets"
echo ""
echo -e "${YELLOW}To clean up all resources:${NC}"
echo "  az group delete --name $RESOURCE_GROUP --yes"
echo ""

# Save outputs to JSON file for reference
echo "$DEPLOYMENT_OUTPUT" > deployment-info.json
echo -e "${GREEN}Full deployment info saved to deployment-info.json${NC}"
