import { Plan, UserProfile, UsageData } from './types';

export const STRINGS = {
  EN: {
    welcome: 'Welcome back,',
    savingsTitle: 'Potential Savings',
    savingsValue: '₦800 Monthly Savings',
    dataHealth: 'Data Health',
    dataHealthDesc: 'Your data drains fast on social apps',
    placeholder: 'Ask ClarityAI...',
    chatInitial: 'Hello {name}! How can I help you save on your MTN plan today?',
    ctaDemo: 'Try Demo',
    ctaLaunch: 'Launch Assistant',
    heroTitle: 'Understand Your MTN Plan. Save More Every Month.',
    heroSub: 'AI powered advisor for smarter data, calls and bundles.',
    whyMyDataFinish: 'Why my data finish fast?',
    comparePlans: 'Compare Pulse Plus vs BizPlus',
    showCheaper: 'Show cheaper bundles',
  },
  PIDGIN: {
    welcome: 'Welcome back,',
    savingsTitle: 'Troway Less Money',
    savingsValue: '₦800 you go save every month',
    dataHealth: 'Data Matter',
    dataHealthDesc: 'Your data dey finish fast for TikTok and Instagram',
    placeholder: 'Check ClarityAI...',
    chatInitial: 'How far {name}! Which MTN plan we go rearrange today?',
    ctaDemo: 'Check am',
    ctaLaunch: 'Start Assistant',
    heroTitle: 'Understnd your MTN Plan. Save better money.',
    heroSub: 'AI wey know road for data, calls and bundles.',
    whyMyDataFinish: 'Why my data dey finish fast?',
    comparePlans: 'Compare Pulse Plus and BizPlus',
    showCheaper: 'Show me cheaper bundles',
  },
  HA: {
    welcome: 'Barka da zuwa,',
    savingsTitle: 'Abin da za a ajiye',
    savingsValue: '₦1,250 Za a ajiye a wata',
    dataHealth: 'Lafiyar Data',
    dataHealthDesc: 'Datanka yana karewa da wuri a kafofin sada zumunta',
    placeholder: 'Tambayi ClarityAI...',
    chatInitial: 'Sannu {name}! Ta yaya zan taimake ki ki rage kashe kudi a MTN yau?',
    ctaDemo: 'Gwada',
    ctaLaunch: 'Fara',
    heroTitle: 'Fahimci Shirin MTN dinka. Ajiye kudi kowane wata.',
    heroSub: 'AI mai ba da shawara don data da kira.',
    whyMyDataFinish: 'Me yasa datana yake karewa da wuri?',
    comparePlans: 'Gwada Pulse da BizPlus',
    showCheaper: 'Nuna min bundles masu rahusa',
  },
  YO: {
    welcome: 'Kaabo,',
    savingsTitle: 'Owo ti o le fipamo',
    savingsValue: '₦1,250 itoju owo lojooṣu',
    dataHealth: 'Ipo Data rẹ',
    dataHealthDesc: 'Data rẹ n tan ni kiakia lori ayelujara',
    placeholder: 'Beere lọwọ ClarityAI...',
    chatInitial: 'Pẹlẹ o {name}! Bawo ni mo ṣe le ran ọ lọwọ lati dinku inawo rẹ loni?',
    ctaDemo: 'Danwo',
    ctaLaunch: 'Wọle',
    heroTitle: 'Loye Eto MTN rẹ. Fi owo pupọ pamọ lojooṣu.',
    heroSub: 'AI oluranlowo fun data ati ipe to daju.',
    whyMyDataFinish: 'Kilode ti data mi fi n tan ni kiakia?',
    comparePlans: 'Fi Pulse we BizPlus',
    showCheaper: 'Ṣafihan awọn bundles ti o din owo',
  },
  IG: {
    welcome: 'Nnọọ,',
    savingsTitle: 'Ego ị ga-echekwa',
    savingsValue: '₦1,250 ego nchekwa kwa ọnwa',
    dataHealth: 'Ahụike Data',
    dataHealthDesc: 'Data gị na-agwụ ngwa ngwa na ntanetị',
    placeholder: 'Jụọ ClarityAI...',
    chatInitial: 'Ndewo {name}! Kedu otu m ga-esi nyere gị aka chekwaa ego na MTN taa?',
    ctaDemo: 'Nwalee',
    ctaLaunch: 'Malite',
    heroTitle: 'Ghotakwuo atụmatụ MTN gị. Chekwaa ego kwa ọnwa.',
    heroSub: 'AI na-enye ndụmọdụ maka data na oku.',
    whyMyDataFinish: 'Gịnị kpatara data m ji agwụ ngwa ngwa?',
    comparePlans: 'Tụlee Pulse na BizPlus',
    showCheaper: 'Gosi m bundles kacha ọnụ ala',
  },
};
