import { Plan, UserProfile, UsageData } from './types';

export const MOCK_USER: UserProfile = {
  name: 'Aisha',
  currentPlanId: 'pulse-flexi',
  monthlySpend: 2000,
  dataBurnRate: 'Medium',
  heavySocialUsage: true,
};

export const PLANS: Plan[] = [
  {
    id: "pulse-flexi",
    name: "MTN Pulse Flexi",
    category: "youth",
    monthlyCost: 2000,
    dataGB: 7,
    callMinutes: 200,
    smsCount: 100,
    validityDays: 30,
    activationCode: "*406#",
    summary: "Youth-focused plan with social media bonuses and flexi rollover data",
    features: [
      "7GB data (5GB standard + 2GB night data 12AM-6AM)",
      "200 minutes MTN-to-MTN calls",
      "100 SMS",
      "Free access to Boomplay music streaming",
      "Data rollover if you recharge before expiry",
      "Birthday bonus: double data on your birthday"
    ],
    bestFor: "Students and young professionals who use social media heavily and want night browsing bonuses",
    limitations: "Night data (2GB) only valid between 12AM and 6AM. Off-net calls cost extra.",
    competitors: ["Airtel SmartConnect", "Glo Beambooster"],
    upsellTo: "mtn-pulse-plus",
    matchScore: 92,
  },
  {
    id: "mtn-pulse-plus",
    name: "MTN Pulse Plus",
    category: "youth",
    monthlyCost: 3500,
    dataGB: 15,
    callMinutes: 400,
    smsCount: 200,
    validityDays: 30,
    activationCode: "*406*2#",
    summary: "Upgraded youth plan with more data and cross-network calls",
    features: [
      "15GB data (12GB standard + 3GB night data)",
      "400 minutes all-network calls",
      "200 SMS",
      "Free WhatsApp and Instagram data (1GB/day)",
      "Data rollover",
      "Free caller tunes"
    ],
    bestFor: "Active social media users and content creators who need more data and cross-network calls",
    limitations: "Social media data (WhatsApp/Instagram) cannot be used for other apps",
    competitors: ["Airtel SmartValue", "Glo Mega Deal"],
    upsellTo: "mtn-xtravalue",
    matchScore: 84,
  },
  {
    id: "mtn-xtravalue",
    name: "MTN XtraValue",
    category: "individual",
    monthlyCost: 5000,
    dataGB: 25,
    callMinutes: 600,
    smsCount: 300,
    validityDays: 30,
    activationCode: "*131*5#",
    summary: "Premium individual plan with large data bundle and unlimited weekend calls",
    features: [
      "25GB data",
      "600 minutes all-network calls",
      "Unlimited weekend calls (Sat-Sun, MTN-to-MTN)",
      "300 SMS",
      "Data rollover",
      "Priority customer support"
    ],
    bestFor: "Working professionals and freelancers with moderate-to-heavy data and calling needs",
    limitations: "Unlimited calls are MTN-to-MTN only on weekends",
    competitors: ["Airtel Unlimited", "9mobile TalkZone Plus"],
    upsellTo: "bizplus-starter",
    matchScore: 76,
  },
  {
    id: "bizplus-starter",
    name: "MTN BizPlus Starter",
    category: "business",
    monthlyCost: 8000,
    dataGB: 50,
    callMinutes: 1000,
    smsCount: 500,
    validityDays: 30,
    activationCode: "*131*8#",
    summary: "Entry-level SME plan with shared data pool for up to 3 lines",
    features: [
      "50GB shared data pool (up to 3 lines)",
      "1000 minutes all-network calls",
      "500 SMS",
      "Business dashboard for usage monitoring",
      "Dedicated SME helpline",
      "Monthly invoice/billing"
    ],
    bestFor: "Small businesses and entrepreneurs with 2-3 employees who need a shared data plan",
    limitations: "Maximum 3 lines. Lines must all be on MTN network.",
    competitors: ["Airtel BizConnect", "Glo Business Starter"],
    upsellTo: "bizplus-pro",
    matchScore: 88,
  },
  {
    id: "bizplus-pro",
    name: "MTN BizPlus Pro",
    category: "business",
    monthlyCost: 20000,
    dataGB: 200,
    callMinutes: 3000,
    smsCount: 2000,
    validityDays: 30,
    activationCode: "*131*9#",
    summary: "Mid-tier SME plan with large shared pool for up to 10 lines and analytics dashboard",
    features: [
      "200GB shared data pool (up to 10 lines)",
      "3000 minutes all-network calls",
      "2000 SMS",
      "Advanced analytics dashboard",
      "Dedicated account manager",
      "Monthly invoice/billing",
      "Priority network access",
      "International roaming (optional add-on)"
    ],
    bestFor: "Growing businesses with 5-10 employees needing heavy data and reliable connectivity",
    limitations: "Maximum 10 lines. International roaming is a separate add-on cost.",
    competitors: ["Airtel SmartBiz", "Glo Business Pro"],
    upsellTo: "bizplus-enterprise",
    matchScore: 92,
  },
  {
    id: "bizplus-enterprise",
    name: "MTN BizPlus Enterprise",
    category: "business",
    monthlyCost: 50000,
    dataGB: 1000,
    callMinutes: 10000,
    smsCount: 5000,
    validityDays: 30,
    activationCode: "Contact MTN Business",
    summary: "Full enterprise plan with unlimited lines, SLA guarantee, and dedicated support",
    features: [
      "1TB shared data pool (unlimited lines)",
      "10,000 minutes all-network calls",
      "5,000 SMS",
      "SLA: 99.9% uptime guarantee",
      "Dedicated account team",
      "API access for usage management",
      "Custom billing cycles",
      "International roaming included",
      "Priority network infrastructure"
    ],
    bestFor: "Large businesses and enterprises with 10+ employees, high data demands, and SLA requirements",
    limitations: "Requires 6-month minimum contract. Setup fee may apply.",
    competitors: ["Airtel Enterprise", "MTN direct corporate contracts"],
    upsellTo: null,
    matchScore: 95,
  },
  {
    id: "mtn-daily-5x5",
    name: "MTN Daily 5x5",
    category: "individual",
    monthlyCost: 150,
    dataGB: 0.15,
    callMinutes: 5,
    smsCount: 10,
    validityDays: 1,
    activationCode: "*131*1#",
    summary: "Daily micro-bundle for casual users who don't use their phone heavily",
    features: [
      "150MB data",
      "5 minutes MTN-to-MTN calls",
      "10 SMS",
      "Valid for 24 hours",
      "No commitment — recharge as needed"
    ],
    bestFor: "Occasional users, backup SIM holders, or users who prefer daily control over spending",
    limitations: "Very limited data. Significantly more expensive per GB than monthly plans.",
    competitors: ["Glo Daily Flexi", "Airtel Daily Plan"],
    upsellTo: "pulse-flexi",
    matchScore: 65,
  }
];

export const USAGE_STATS: UsageData[] = [
  { category: 'Social Media', percentage: 60, color: '#FFCC00' },
  { category: 'YouTube', percentage: 20, color: '#003366' },
  { category: 'Browsing', percentage: 10, color: '#4ADE80' },
  { category: 'Updates', percentage: 10, color: '#94A3B8' },
];

export const STRINGS = {
  EN: {
    welcome: 'Welcome back,',
    savingsTitle: 'Potential Savings',
    savingsValue: '₦800 Monthly Savings',
    dataHealth: 'Data Health',
    dataHealthDesc: 'Your data drains fast on social apps',
    placeholder: 'Ask ClarityAI...',
    chatInitial: 'Hello Aisha! How can I help you save on your MTN plan today?',
    ctaDemo: 'Try Demo',
    ctaLaunch: 'Launch Assistant',
    heroTitle: 'Understand Your MTN Plan. Save More Every Month.',
    heroSub: 'AI powered advisor for smarter data, calls and bundles.',
    whyMyDataFinish: 'Why my data finish fast?',
    comparePlans: 'Compare Pulse Plus vs BizPlus',
    showCheaper: 'Show cheaper bundles',
  },
  PIDGIN: {
    welcome: 'Welcome back,',
    savingsTitle: 'Troway Less Money',
    savingsValue: '₦800 you go save every month',
    dataHealth: 'Data Matter',
    dataHealthDesc: 'Your data dey finish fast for TikTok and Instagram',
    placeholder: 'Check ClarityAI...',
    chatInitial: 'How far Aisha! Which MTN plan we go rearrange today?',
    ctaDemo: 'Check am',
    ctaLaunch: 'Start Assistant',
    heroTitle: 'Understnd your MTN Plan. Save better money.',
    heroSub: 'AI wey know road for data, calls and bundles.',
    whyMyDataFinish: 'Why my data dey finish fast?',
    comparePlans: 'Compare Pulse Plus and BizPlus',
    showCheaper: 'Show me cheaper bundles',
  },
  HA: {
    welcome: 'Barka da zuwa,',
    savingsTitle: 'Abin da za a ajiye',
    savingsValue: '₦1,250 Za a ajiye a wata',
    dataHealth: 'Lafiyar Data',
    dataHealthDesc: 'Datanka yana karewa da wuri a kafofin sada zumunta',
    placeholder: 'Tambayi ClarityAI...',
    chatInitial: 'Sannu Aisha! Ta yaya zan taimake ki ki rage kashe kudi a MTN yau?',
    ctaDemo: 'Gwada',
    ctaLaunch: 'Fara',
    heroTitle: 'Fahimci Shirin MTN dinka. Ajiye kudi kowane wata.',
    heroSub: 'AI mai ba da shawara don data da kira.',
    whyMyDataFinish: 'Me yasa datana yake karewa da wuri?',
    comparePlans: 'Gwada Pulse da BizPlus',
    showCheaper: 'Nuna min bundles masu rahusa',
  },
  YO: {
    welcome: 'Kaabo,',
    savingsTitle: 'Owo ti o le fipamo',
    savingsValue: '₦1,250 itoju owo lojooṣu',
    dataHealth: 'Ipo Data rẹ',
    dataHealthDesc: 'Data rẹ n tan ni kiakia lori ayelujara',
    placeholder: 'Beere lọwọ ClarityAI...',
    chatInitial: 'Pẹlẹ o Aisha! Bawo ni mo ṣe le ran ọ lọwọ lati dinku inawo rẹ loni?',
    ctaDemo: 'Danwo',
    ctaLaunch: 'Wọle',
    heroTitle: 'Loye Eto MTN rẹ. Fi owo pupọ pamọ lojooṣu.',
    heroSub: 'AI oluranlowo fun data ati ipe to daju.',
    whyMyDataFinish: 'Kilode ti data mi fi n tan ni kiakia?',
    comparePlans: 'Fi Pulse we BizPlus',
    showCheaper: 'Ṣafihan awọn bundles ti o din owo',
  },
  IG: {
    welcome: 'Nnọọ,',
    savingsTitle: 'Ego ị ga-echekwa',
    savingsValue: '₦1,250 ego nchekwa kwa ọnwa',
    dataHealth: 'Ahụike Data',
    dataHealthDesc: 'Data gị na-agwụ ngwa ngwa na ntanetị',
    placeholder: 'Jụọ ClarityAI...',
    chatInitial: 'Ndewo Aisha! Kedu otu m ga-esi nyere gị aka chekwaa ego na MTN taa?',
    ctaDemo: 'Nwalee',
    ctaLaunch: 'Malite',
    heroTitle: 'Ghotakwuo atụmatụ MTN gị. Chekwaa ego kwa ọnwa.',
    heroSub: 'AI na-enye ndụmọdụ maka data na oku.',
    whyMyDataFinish: 'Gịnị kpatara data m ji agwụ ngwa ngwa?',
    comparePlans: 'Tụlee Pulse na BizPlus',
    showCheaper: 'Gosi m bundles kacha ọnụ ala',
  },
};
